# Generated by Django 5.0 on 2023-12-11 10:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='designation',
            field=models.CharField(choices=[('SE', 'Software Engineer'), ('SSE', 'Senior Software Engineer'), ('TL', 'Team Lead'), ('Manager', 'Manager'), ('CEO', 'CEO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 10, 3, 15, 37854)),
        ),
    ]
