# Generated by Django 5.0 on 2023-12-11 13:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 13, 18, 27, 709352)),
        ),
    ]
