# Generated by Django 5.0 on 2023-12-11 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeedetails_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 14, 2, 39, 827648)),
        ),
    ]
