# Generated by Django 5.0 on 2023-12-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_email_alter_employeedetails_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 14, 10, 12, 111199)),
        ),
    ]
